### ISSUE TITLE
What version of make does mkincl target?

### ISSUE THREAD

**Issue by ghost** [carlsmedstad/mkincl#1]
What version of make are you targeting with mkincl? I ask because [GNU make already has the ability to include other makefiles][0]. So does the make utility included with [OpenBSD][1].

[0]: https://www.gnu.org/software/make/manual/html_node/Include.html
[1]: https://man.openbsd.org/make

**Comment by carlsmedstad** [comment]
Ah, this might be a point of confusion around the name.

mkincl is a way to download and use Makefiles that are not **locally available**, rather than an implementation of the `include` keyword.

**Comment by ghost** [comment]
I might not have given sufficient attention to the readme file. It looks like this is version-agnostic, and is intended mainly for accessing makefiles in separate repositories. It makes sense now.

I like this, even though it isn't of immediate use to me. Glad to see the classic make tool getting more attention; I do prefer it to more modern build systems like the ones that have sprung up around nodejs.
